image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

stages:
  - "Maven Build"

Publishing to Bintray:
  stage: "Maven Build"
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy
  only:
    - master